@extends('layout.master')
@section('content')
@include('layout.bradecrumb')
	<div class="row ">
		<h3 class="page_heading">Student DashBoard</h3>
		<div class="col-md-6">
			<div class="panel panel-info">
			  <div class="panel-heading">Sutdent Information</div>
			  <div class="panel-body"><!--info body-->

			  </div><!--/info body-->
			</div>
		</div>
		<div class="col-md-3">
			<div class="panel panel-info">
			  <div class="panel-heading">Student Picture</div>
			  <div class="panel-body">
			  	
			  </div>
			</div>
		</div>
		
	</div>

@stop